CREATE SCHEMA BazaPogody;
CREATE TABLE [BazaPogody].[Pogoda]
( 
    [ID] INT IDENTITY(1,1) NOT NULL, 
	[CityId] INT NOT NULL;
    [City] NVARCHAR(50) NOT NULL, 
    [Country] NVARCHAR(50) NOT NULL,
	[Temperature] Float NOT NULL,
	[Icon] Image,
	CONSTRAINT [PK_BU] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
--ALTER TABLE BazaPogody.Pogoda ADD CityId int NOT NULL;