//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pogodynka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pogoda
    {
        public int ID { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public double Temperature { get; set; }
        public byte[] Icon { get; set; }
        public int CityId { get; set; }
    }
}
